#cloud-config
package_upgrade: true
packages:
  - docker
  - postgresql
write_files:
  - encoding: b64
    content: ${b64_docker_compose_config}
    path: /opt/docker-compose.yaml
runcmd:
  - mkdir /opt/postgres
  - mkdir /opt/nginx
  - aws s3 cp s3://psider-2021-10-24/nginx/nginx.conf /opt/nginx/nginx.conf
  - aws s3 cp s3://psider-2021-10-24/nginx/psider.crt /opt/nginx/psider.crt
  - aws s3 cp s3://psider-2021-10-24/nginx/psider.decrypted.key /opt/nginx/psider.decrypted.key
  - aws s3 cp s3://psider-2021-10-24/postgres/seed.sql /opt/postgres/seed.sql
  - sed -i $'1s/^\uFEFF//' /opt/postgres/seed.sql
  - psql postgresql://${db_username}:${db_password}@${db_host}:${db_port}/${db_name} -f /opt/postgres/seed.sql
  - sudo service docker start
  - sudo usermod -a -G docker ec2-user
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - docker-compose -f /opt/docker-compose.yaml up -d
