version: "3.9"
services:
  nginx:
    image: nginx:1.20.0
    volumes:
      - /opt/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /opt/nginx/psider.crt:/etc/ssl/certs/psider.crt:ro
      - /opt/nginx/psider.decrypted.key:/etc/ssl/certs/psider.decrypted.key:ro
    ports:
      - 80:80
      - 443:443
    networks:
      - psider_local
    depends_on:
      - psidercms
      - psidercmsui

  psidercms:
    image: psat01/psider
    volumes:
      - images_data:/App/wwwroot/images/:rw
    #    ports:
    #      - 8080:80
    environment:
      "ConnectionStrings:DefaultConnection": "Host=${db_host};Port=${db_port};Database=${db_name};Username=${db_username};Password=${db_password}"
      "ASPNETCORE_ENVIRONMENT": "Development"
    networks:
      - psider_local # port 80 is exposed
  psidercmsui:
    image: psat01/psider-cms-ui
    #    ports:
    #      - 4200:4200
    networks:
      - psider_local # port 4200 is exposed

networks:
  psider_local:
    name: psider-local

volumes:
  images_data:
