version: "3.9"
services:
  nginx:
    image: nginx:1.20.0
    volumes:
      - /opt/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /opt/nginx/includes/proxy.conf:/etc/nginx/includes/proxy.conf:ro
      - /opt/nginx/certs/cloudflare.crt:/etc/ssl/certs/cloudflare.crt:ro
      - /opt/nginx/certs/cloudflare.key:/etc/ssl/certs/cloudflare.key:ro
    ports:
      - 80:80
      - 443:443
    networks:
      - psider_local
    depends_on:
      - psidercms
      - psidercmsui
      - webdemo
      - webpreview

  psidercms:
    image: psat01/psider
    volumes:
      - images_data:/App/wwwroot/images/:rw
    #    ports:
    #      - 8080:80
    environment:
      "ConnectionStrings:DefaultConnection": "Host=${db_props.host};Port=${db_props.port};Database=${db_props.name};Username=${db_props.username};Password=${db_props.password}"
      "ASPNETCORE_ENVIRONMENT": "Development"
    networks:
      - psider_local # port 80 is exposed

  psidercmsui:
    image: psat01/psider-cms-ui
    #    ports:
    #      - 4200:4200
    networks:
      - psider_local # port 4200 is exposed

  webdemo:
    image: psat01/psider-web
    #    ports:
    #      - 3000:3000
    volumes:
      - images_data:/app/public/images/:ro
    networks:
      - psider_local

  webpreview:
    image: psat01/psider-web
    #    ports:
    #      - 3001:3000
    volumes:
      - images_data:/app/public/images/:ro
    entrypoint: "next dev"
    networks:
      - psider_local

networks:
  psider_local:
    name: psider-local

volumes:
  images_data:
