version: "3.9"
services:
  nginx:
    image: nginx:1.20.0
    volumes:
      - /opt/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /opt/nginx/includes/proxy.conf:/etc/nginx/includes/proxy.conf:ro
      - /opt/nginx/certs/celestial.blue.crt:/etc/ssl/certs/celestial.blue.crt:ro
      - /opt/nginx/certs/celestial.blue.key:/etc/ssl/certs/celestial.blue.key:ro
    ports:
      - 80:80
      - 443:443
    networks:
      - psider_local
    depends_on:
      - psidercms
      - psidercmsui
      - webdemo

  psidercms:
    image: psat01/psider
    volumes:
      - images_data:/App/wwwroot/images/:rw
    #    ports:
    #      - 8080:80
    environment:
      "ConnectionStrings:DefaultConnection": "Host=${db_props.host};Port=${db_props.port};Database=${db_props.name};Username=${db_props.username};Password=${db_props.password}"
      "SeedUserPW": "SuperSafePassw0rd!"
      "ASPNETCORE_ENVIRONMENT": "Development"
    networks:
      - psider_local # port 80 is exposed

  psidercmsui:
    image: psat01/psider-cms-ui
    #    ports:
    #      - 4200:80
    networks:
      - psider_local # port 4200 is exposed
    depends_on:
      - psidercms

  webdemo:
    image: psat01/psider-web
    #    ports:
    #      - 3000:3000
    volumes:
      - images_data:/app/public/images/:ro
    networks:
      - psider_local
    depends_on:
      - psidercms
      - psidercmsui

networks:
  psider_local:
    name: psider-local

volumes:
  images_data:
